---

 - include: setup-hostname.yml
   when: hostname is defined
 
 - include: install-prereqs.yml
 
 - include: install-docker.yml
 
 - include: configure-docker.yml
 
 - name: Restart docker sockets
   systemd:
     name: docker.socket
     daemon_reload: yes
     state: restarted
   sudo: yes
   sudo_user: root

 - name: Run a hello-world Docker container
   shell: docker run --rm hello-world 
   sudo: yes
   sudo_user: root

 - name: Add user to docker group
   user:
     name: '{{ansible_env.USER}}'
     groups: docker
     append: yes
   when: ansible_env.USER != 'root'
   sudo: yes
   sudo_user: root

 - name: Make user-local bin directories
   file: 
     path: ~/bin 
     state: directory

